version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres_db_golang
    restart: always
    ports:
      - "5428:5432"
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

